CREATE DATABASE IF NOT EXISTS fittrack CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fittrack;

CREATE TABLE IF NOT EXISTS USER (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  date_of_birth DATE NULL,
  gender VARCHAR(10) NULL,
  height_cm DECIMAL(5,2) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WORKOUT (
  workout_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  workout_type VARCHAR(50) NOT NULL,
  duration_minutes INT NOT NULL,
  intensity VARCHAR(20) NOT NULL,
  calories_burned INT NULL,
  workout_date DATE NOT NULL,
  notes VARCHAR(255) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MEAL (
  meal_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  meal_type VARCHAR(20) NOT NULL,
  food_name VARCHAR(100) NOT NULL,
  calories INT NOT NULL,
  protein_g DECIMAL(5,2) NULL,
  carbs_g DECIMAL(5,2) NULL,
  fat_g DECIMAL(5,2) NULL,
  meal_date DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GOAL (
  goal_id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  goal_type VARCHAR(50) NOT NULL,
  target_value DECIMAL(6,2) NOT NULL,
  current_value DECIMAL(6,2) NULL DEFAULT 0,
  start_date DATE NOT NULL,
  target_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GOAL_PROGRESS (
  log_id INT AUTO_INCREMENT PRIMARY KEY,
  goal_id INT NOT NULL,
  log_date DATE NOT NULL,
  value DECIMAL(6,2) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (goal_id) REFERENCES GOAL(goal_id) ON DELETE CASCADE
);