import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Icon from '../components/Icon';
import { useAuth } from '../context/AuthContext';

export default function Register(){
 const {register}=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',password:'',confirm:''}); const [terms,setTerms]=useState(false); const [marketing,setMarketing]=useState(false); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const strength=[form.password.length>=8,/[A-Z]/.test(form.password),/[0-9]/.test(form.password),/[^A-Za-z0-9]/.test(form.password)].filter(Boolean).length;
 const submit=async e=>{e.preventDefault();setError('');if(!terms)return setError('Please accept the Terms of Service and Privacy Policy.');if(form.password!==form.confirm)return setError('Passwords must match.');const parts=form.name.trim().split(/\s+/);if(parts.length<2)return setError('Please enter your first and last name.');setBusy(true);try{await register({first_name:parts[0],last_name:parts.slice(1).join(' '),email:form.email,password:form.password});navigate('/dashboard',{replace:true});}catch(err){setError(err.message);}finally{setBusy(false);}};
 return <><Navbar publicPage/><div className="auth-page"><div className="auth-stack"><div className="auth-card"><div className="auth-header"><div className="auth-mark">ϟ</div><h1>Create your account</h1><p>Join FitTrack and start your fitness journey</p></div><div className="auth-divider"/><form className="auth-form" onSubmit={submit}>
 <label className="field"><span className="field-label">Full Name <span className="muted small">(required)</span></span><input required placeholder="John Doe" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><span className="field-hint">Enter your first and last name</span></label>
 <label className="field"><span className="field-label">Email Address <span className="muted small">(required)</span></span><input required type="email" placeholder="you@example.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><span className="field-hint">We'll use this address for your account</span></label>
 <label className="field"><span className="field-label">Password <span className="muted small">(required)</span></span><div className="password-wrap"><input required minLength={8} type={show?'text':'password'} placeholder="Create a strong password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" className="password-toggle" onClick={()=>setShow(!show)}><Icon name="eye" size={15}/></button></div><div className="strength">{[0,1,2,3].map(i=><span key={i} className={i<strength?'filled':''}/>)}</div><span className="field-hint">Use 8+ characters, an uppercase letter, a number and a special character.</span></label>
 <label className="field"><span className="field-label">Confirm Password <span className="muted small">(required)</span></span><input required type={show?'text':'password'} placeholder="Re-enter your password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label>
 <label className="checkbox-row"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I agree to the <span className="auth-link">Terms of Service</span> and <span className="auth-link">Privacy Policy</span></span></label>
 <label className="checkbox-row"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span>Send me fitness tips, updates, and promotional emails <span className="muted">(optional)</span></span></label>
 {error&&<div className="alert" role="alert">{error}</div>}<button className="button button-dark button-full" disabled={busy}>{busy?'Creating account…':<><Icon name="plus" size={14}/> Create Free Account</>}</button></form>
 <div className="auth-or">or register with</div><div className="social-grid"><button className="button button-outline" type="button" disabled>G&nbsp; Google</button><button className="button button-outline" type="button" disabled>●&nbsp; Apple</button></div><div className="auth-foot">Already have an account? <Link className="auth-link" to="/login">Sign in here</Link></div>
 </div><div className="security-note"><Icon name="shield" size={12}/> Secured with 256-bit SSL encryption. Your data is safe.</div></div></div></>;
}
